stages:
  - build_image


default:
  before_script:
    - export PROJECTNAME="triton_model_status"
    - export NAME_FROM_BRANCH=$(echo $CI_COMMIT_REF_NAME | cut -d'-' -f 1)
    - export VERSION_IN_CONFIG=$(cat version)
    - export IMAGE="nexus-dcr.avlab.dev/$PROJECTNAME/$NAME_FROM_BRANCH:$VERSION_IN_CONFIG"
    - export BRANCH=`echo "$NAME_FROM_BRANCH" | sed  's/develop/dev/' | sed  's/main/prod/'`
    #- export NAMESPACE="vp-reception-$BRANCH"
    - export NAMESPACE="vp-reception-dev"
    #- export BASE_HOST="nlp-lawyer-recom-$BRANCH.nlp.avlab.dev"
    - echo "Image = $IMAGE for $NAMESPACE"

build_image:
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$STAGE_KEY == "from_multy_ci"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^(develop|stage|main)$/'
      changes:
        - version

  script:
    - echo $STAGE_KEY
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"nexus-dcr.avlab.dev\":{\"username\":\"$NEXUS_MAVEN_USER\",\"password\":\"$NEXUS_MAVEN_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cp $CI_SERVER_TLS_CA_FILE /kaniko/ssl/certs/additional-ca-cert-bundle.crt
    - cp $CI_SERVER_TLS_CA_FILE ./avlab_ca.crt
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --cache=false
      --destination $IMAGE

#kube-deploy:
#  only:
#  - /^develop$/
#  stage:  kube
#  image:
#    name: "$KUBDEPLOYER_IMAGE_NAME"
#  script:
#    - echo $KUBECONFIG_DATA | base64 -d > /tmp/kubeconfig
#    - helm --kubeconfig /tmp/kubeconfig
#      -n $NAMESPACE upgrade -i
#      --set namespace="$NAMESPACE"
#      --set image.image="$IMAGE"
#      -f values.yaml
#      $PROJECTNAME
#      .
