---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-model-status
  namespace: vp-reception-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-model-status
  template:
    metadata:
      labels:
        app: triton-model-status
    spec:
      containers:
      - name: triton-model-status
        image: nexus-dcr.avlab.dev/triton_model_status/main:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: triton-model-status-service
  namespace: vp-reception-dev
  labels:
    app: triton-model-status
spec:
  clusterIP: None
  ports:
    - name: triton-model-status-metrics
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: triton-model-status
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton-model-status
  namespace: vp-reception-dev
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: triton-model-status
  endpoints:
  - port: triton-model-status-metrics